# Generated by Django 3.0.7 on 2020-07-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='msg',
            field=models.TextField(verbose_name='Question'),
        ),
    ]
